/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CButton: typeof import('./src/components/common/CButton.vue')['default']
    DebugInfo: typeof import('./src/components/DebugInfo.vue')['default']
    IconAuto: typeof import('./src/components/icon/IconAuto.vue')['default']
    IconClose: typeof import('./src/components/icon/IconClose.vue')['default']
    IconDownload: typeof import('./src/components/icon/IconDownload.vue')['default']
    IconExpand: typeof import('./src/components/icon/IconExpand.vue')['default']
    IconFunnelSolid: typeof import('./src/components/icon/IconFunnelSolid.vue')['default']
    IconGithub: typeof import('./src/components/icon/IconGithub.vue')['default']
    IconInfo: typeof import('./src/components/icon/IconInfo.vue')['default']
    IconLeft: typeof import('./src/components/icon/IconLeft.vue')['default']
    IconLoading: typeof import('./src/components/icon/IconLoading.vue')['default']
    IconMenu: typeof import('./src/components/icon/IconMenu.vue')['default']
    IconMoon: typeof import('./src/components/icon/IconMoon.vue')['default']
    IconOpen: typeof import('./src/components/icon/IconOpen.vue')['default']
    IconRight: typeof import('./src/components/icon/IconRight.vue')['default']
    IconSearch: typeof import('./src/components/icon/IconSearch.vue')['default']
    IconShrink: typeof import('./src/components/icon/IconShrink.vue')['default']
    IconStack: typeof import('./src/components/icon/IconStack.vue')['default']
    IconSun: typeof import('./src/components/icon/IconSun.vue')['default']
    IconTablet: typeof import('./src/components/icon/IconTablet.vue')['default']
    IconTag: typeof import('./src/components/icon/IconTag.vue')['default']
    IconTitle: typeof import('./src/components/icon/IconTitle.vue')['default']
    IconUser: typeof import('./src/components/icon/IconUser.vue')['default']
    ImageInfo: typeof import('./src/components/ImageInfo.vue')['default']
    ImageViewer: typeof import('./src/components/ImageViewer.vue')['default']
    MasonryItem: typeof import('./src/components/masonry/MasonryItem.vue')['default']
    MasonryView: typeof import('./src/components/masonry/MasonryView.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Sidebar: typeof import('./src/components/sidebar/Sidebar.vue')['default']
    SidebarBlock: typeof import('./src/components/sidebar/SidebarBlock.vue')['default']
    SidebarHead: typeof import('./src/components/sidebar/SidebarHead.vue')['default']
    SidebarMask: typeof import('./src/components/sidebar/SidebarMask.vue')['default']
    Switch: typeof import('./src/components/common/Switch.vue')['default']
    TextBox: typeof import('./src/components/common/TextBox.vue')['default']
    Tip: typeof import('./src/components/Tip.vue')['default']
  }
}
