/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonCommon: typeof import('./src/components/Button/common.vue')['default']
    IconAuto: typeof import('./src/components/Icon/auto.vue')['default']
    IconClose: typeof import('./src/components/Icon/close.vue')['default']
    IconDownload: typeof import('./src/components/Icon/download.vue')['default']
    IconExpand: typeof import('./src/components/Icon/expand.vue')['default']
    IconFunnelSolid: typeof import('./src/components/Icon/funnelSolid.vue')['default']
    IconGithub: typeof import('./src/components/Icon/github.vue')['default']
    IconLeft: typeof import('./src/components/Icon/left.vue')['default']
    IconLoading: typeof import('./src/components/Icon/loading.vue')['default']
    IconMenu: typeof import('./src/components/Icon/menu.vue')['default']
    IconMoon: typeof import('./src/components/Icon/moon.vue')['default']
    IconOpen: typeof import('./src/components/Icon/open.vue')['default']
    IconRight: typeof import('./src/components/Icon/right.vue')['default']
    IconSearch: typeof import('./src/components/Icon/search.vue')['default']
    IconShrink: typeof import('./src/components/Icon/shrink.vue')['default']
    IconSun: typeof import('./src/components/Icon/sun.vue')['default']
    IconTablet: typeof import('./src/components/Icon/tablet.vue')['default']
    ImageViewer: typeof import('./src/components/ImageViewer/index.vue')['default']
    MasonryView: typeof import('./src/components/MasonryView/index.vue')['default']
    MasonryViewItem: typeof import('./src/components/MasonryView/item.vue')['default']
    Navbar: typeof import('./src/components/Navbar/index.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar/index.vue')['default']
    SidebarBlock: typeof import('./src/components/Sidebar/block.vue')['default']
    SidebarHead: typeof import('./src/components/Sidebar/head.vue')['default']
    Switch: typeof import('./src/components/Switch/index.vue')['default']
    TextBox: typeof import('./src/components/TextBox/index.vue')['default']
  }
}
