/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconClose: typeof import('./src/components/Icon/close.vue')['default']
    IconExpand: typeof import('./src/components/Icon/expand.vue')['default']
    IconFunnelSolid: typeof import('./src/components/Icon/funnelSolid.vue')['default']
    IconGithub: typeof import('./src/components/Icon/github.vue')['default']
    IconLeft: typeof import('./src/components/Icon/left.vue')['default']
    IconMenu: typeof import('./src/components/Icon/menu.vue')['default']
    IconMoon: typeof import('./src/components/Icon/moon.vue')['default']
    IconRight: typeof import('./src/components/Icon/right.vue')['default']
    IconShrink: typeof import('./src/components/Icon/shrink.vue')['default']
    IconSun: typeof import('./src/components/Icon/sun.vue')['default']
    ImageViewer: typeof import('./src/components/ImageViewer/index.vue')['default']
    MasonryView: typeof import('./src/components/MasonryView/index.vue')['default']
    MasonryViewItem: typeof import('./src/components/MasonryView/item.vue')['default']
    Navbar: typeof import('./src/components/Navbar/index.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar/index.vue')['default']
  }
}
